force-app/main/default/objects/Account/fields/Offer_Name__c.field-meta.xml
<CustomField>
    <fullName>Offer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offer Name</label>
    <referenceTo>Offer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/triggers/AccountTriggerHandler.cls
/**
 * Created by Yulia Yakushenkova on 20.09.2019.
 */

public with sharing class AccountTriggerHandler {
    public static void delAccountRelationship(List<Account> accountsToDelete){
        List<Offer__c> offersToDelete = new List<Offer__c>();
        for(Account delAccount : accountsToDelete){
            Offer__c delOffer = [SELECT Id FROM Offer__c WHERE Id =: delAccount.Offer_Name__c];
            offersToDelete.add(delOffer);
        }
        try{
            delete offersToDelete;
            delete accountsToDelete;
        }catch(Exception e){

        }
    }
}