force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>AO-{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Статус</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Не согласовано</fullName>
                <default>true</default>
                <label>Не согласовано</label>
            </value>
            <value>
                <fullName>Согласовано</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OfferRestService.cls
/**
 * Created by Yulia Yakushenkova on 20.09.2019.
 */

@RestResource(UrlMapping='/offerstatus')
global with sharing class OfferRestService {

    @HttpGet
    global static List<Offer__c> getRecord() {
        return [SELECT Id, RestName__c, Status__c FROM Offer__c];
    }

    @HttpPost
    global static Offer__c getOfferStatus(String Id) {
        Offer__c offer = [SELECT Id, RestName__c, Status__c FROM Offer__c WHERE Id =: Id];
        //return JSON.serialize(offer);
        return offer;
    }
}